### ISSUE TITLE
Add extension options

### ISSUE THREAD

**Issue by m-schwarzinger** [R35007/create-app-support#1]
Hello, 
your extension is great, excactly what I was looking for, but there is one thing missing for me, could you please add the ability to create custom entries?

**Comment by R35007** [comment]
Sure. Can you please explain what you mean by custom entries?

**Comment by m-schwarzinger** [comment]
I guess the best way to explain it is by this example from another addon which implemented something similar.

That Extension makes it possible to add own entries with the settings.json where it makes it possible to add a command with parameters. Sadly that Extension is not as good as yours and just provides the ability to create projects via npx and not with maven, composer or dotnet. 

```
{
  "newProject.generators": [
    {
      "id": "create-liuli",
      "title": "liuli",
      "package": "create-liuli",
      "command": "create-liuli",
      "configs": [
        {
          "type": "select",
          "name": "template",
          "label": "Template",
          "default": "lib",
          "options": [
            { "label": "lib", "value": "lib" },
            { "label": "cli", "value": "cli" }
          ]
        },
        {
          "type": "checkbox",
          "name": "overwrite",
          "label": "Overwrite",
          "default": true
        }
      ]
    }
  ]
}
```


So let's say I want to create an entry for C# I would add something like this:

```
{
  "newProject.generators": [
    {
      "title": "C#",
      "icon": "[link to C# logo]",
      "command": "dotnet new",
      "configs": [
        {
          "type": "select",
          "label": "ProjectType",
          "default": "console",
          "options": [
            { "label": "console", "value": "console" },
            { "label": "classlib", "value": "classlib" }
          ]
        }
      ]
    }
  ]
}
```

**Comment by R35007** [comment]
```jsonc
{
    "appName": "Angular",
    "fieldProps": [
        {
            "id": "app-id",
            "label": "App Id",
            "type": "text-field",
            "value": "hello-world",
            "isRequired": true,
            "placeholder": "Can have lowercase alphabets, numbers and minus (-). No spaces or special chars are allowed."
        },
        {
            "id": "stylesheet-format",
            "label": "Stylesheet Format",
            "type": "dropdown",
            "value": "css",
            "options": [
                {
                    "label": "CSS",
                    "value": "css"
                },
                {
                    "label": "SCSS",
                    "value": "scss"
                }
            ]
        },
        {
            "id": "folder-location",
            "label": "App Folder Location",
            "type": "browse",
            "description": "If not provided the app creates in the active workspace folder."
        }
    ],
    "description": "Angular is a platform and framework for building single-page client applications using HTML and TypeScript",
    "logoPath": "https://raw.githubusercontent.com/R35007/create-app-support/master/images/angular.png",
    "scriptPath": [
        "media",
        "scripts",
        "angular.js"
    ],
    "isSelected": false,
    "prerequisites": [
        {
            "label": "node",
            "href": "https://nodejs.org/en/",
            "description": "https://nodejs.org/en/"
        },
        {
            "label": "@angular/cli",
            "command": "npm install -g @angular/cli",
            "description": "Click here to install @angular/cli globally"
        }
    ],
    "additionalCommands": [
        {
            "label": "ng new",
            "command": "ng new",
            "description": "Click here to create the angular app using cli prompts"
        },
        {
            "label": "check cli version",
            "command": "ng --version",
            "description": "Click here to check cli version"
        },
        {
            "label": "cli help",
            "command": "ng new --help",
            "description": "Click here to know more cli configurations"
        }
    ],
    "resources": [
        "<a href=\"https://angular.io/\">Home Page</a>",
        "<a href=\"https://angular.io/guide/setup-local\">Getting Started</a>",
        "<a href=\"https://www.npmjs.com/package/@angular/cli\">Npm Package</a>",
        "<a href=\"https://angular.io/tutorial\">Tutorial</a>"
    ],
    "tags": [
        "angular",
        "ui",
        "web",
        "framework",
        "frontend",
        "webapp"
    ]
}
```

**Comment by R35007** [comment]
As shown above, I am already using a similar approach o generate a dynamic form using Json schema. The only thing I am missing out is that common script to handle all forms. Currently I have a separate script file for each app forms. Once I generalize that we can make this as dynamic.

It's a long way to go. I will try to work on that.
Meanwhile If you have any specific app to add on, please give me the Json file as shown above. I will add it for now.

**Comment by R35007** [comment]
But till, I am Just running the commands in command line. I am sure about maven or composer or dotnet. Not sure it will work in CLI.

**Comment by R35007** [comment]
Closing this issue as there is not scope for this now.

**Comment by R35007** [comment]
Hi, @hackandcode-at 

With the new version [4.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.create-app),
we can now add our own custom app template with lot more features. 

Please try this and give me feedback.

Thanks,
Siva 😊

**Comment by m-schwarzinger** [comment]
Hi, Looks great!
The creation of the custom template is a bit much, but that's okay because it is necessary for that kind of extension.

**Comment by R35007** [comment]
Except, appName and commandTemplate all other props are optional.

again for the fields only label is mandated and all other props are
optional.

Example of simple config.

{
    "appName": "My App Name",
    "commandTemplate": "npx creat-react-app ${fields.appId}"
     "fields": {
           "appId": {
                "label": "App Id"
            }
      }
}

**Comment by R35007** [comment]
@hackandcode-at 

Except the `appName` and `commandTemplate` all other props are optional.
For fields except the `label` and `type` all other props are optional.

Example of simple config.

```json
{
    "appName": "My App Name",
    "commandTemplate": "npx creat-react-app ${fields.appId}"
     "fields": {
           "appId": {
                "label": "App Id",
                 "type": "textbox"
            }
      }
}
```

If you like this extension can u please support us by giving a rating and review in the vscode marketplace extension.

Thanks 😊

**Comment by m-schwarzinger** [comment]
@R35007 

I am currently creating a few more features for this project.

can add the hacktoberfest-tag in the source code branch?

**Comment by R35007** [comment]
Hi @hackandcode-at ,

I am not sure what is the benefit from adding that tag. Can you please explain.

I have updated the extensions with lot more features. please take a look.
https://marketplace.visualstudio.com/items?itemName=Thinker.create-app&ssr=false#overview
