### ISSUE TITLE
Suggestion: Add Vite

### ISSUE THREAD

**Issue by felipfr** [R35007/create-app-support#2]
I want to leave a suggestion: add Vite and more options in Next.js, such as using Turbopack and the app folder.

Thanks.

**Comment by R35007** [comment]
@felipfr ,

Vite don't have a ci option to create a boilerplate.  
Please let me know if you have any document for it.

**Comment by R35007** [comment]
Hi, @felipfr 

With the new version [4.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.create-app),
We can now add our own custom app template with lot more features. 
Also added `Vite` app in the extension.

For any more configuration or modification try giving the custom app configuration Json with the same app name. This overrides the existing configuration and can be modified as our wish.

Please try this and give me your feedback.

Thanks,
Siva 😊
