### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by ProfessorManhattan** [R35007/create-app-support#3]
Hey, I like the look and feel of this app. Is there source code available for it? Also, how can we add in our own app templates?

**Comment by R35007** [comment]
@ProfessorManhattan ,

Please raise a PR to this repo [create-app-vscode-extension](https://github.com/R35007/create-app-vscode-extension) for your custom app template.

**Comment by R35007** [comment]
Hi, @ProfessorManhattan 

With the new version [4.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.create-app),
We can now add our own custom app template with lot more features. 

For any more configuration or modification try giving the custom app configuration Json with the same app name. 
This overrides the existing configuration and can be modified as our wish.

Please try this and give me your feedback.

Thanks,
Siva 😊
